version: '3.8'

services:

  backend:
    image: theaks/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ecommerce-network

  db:
    image: theaks/db:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "QWERTY"
    networks:
     - ecommerce-network
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    image: theaks/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecommerce-network
    environment:
      - VITE_API_URL=http://localhost:8080

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data: